#!/bin/bash 

#!/bin/bash

# Get the absolute path of the current working directory
cwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Print the absolute path
echo "Current working directory: $cwd" 

h
